### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by w8970** [t-paul/kcemu#2]
I was unable to build the software (cloned from current master branch) on Debian GNU/Linux 10, because there is no "configure" script in the main dir.

README states one has to issue command "./configure" first.

Even a try to create it from configure.ac with "autoconf" did not help. The resulting configure script does not work, see:

--------------------------------------------------------------------------
$ git clone https://github.com/t-paul/kcemu.git
Klone nach 'kcemu' ...
remote: Enumerating objects: 8528, done.
remote: Total 8528 (delta 0), reused 0 (delta 0), pack-reused 8528
Empfange Objekte: 100% (8528/8528), 9.27 MiB | 2.93 MiB/s, Fertig.
Löse Unterschiede auf: 100% (6620/6620), Fertig.
$ cd kcemu/
$ ./configure
bash: ./configure: Datei oder Verzeichnis nicht gefunden
$ ls
ABOUT-NLS  AUTHORS    conf    configure.ac  COPYING.de        debian  doc     include  intl               Makefile.am  mkinstalldirs  po      README.de  rpm    src    test    TODO
asm        ChangeLog  config  COPYING       cross-compile.sh  disks   images  INSTALL  KCemuSetup.iss.in  man          NEWS           README  roms       setup  tapes  THANKS  VERSION
$ autoconf 
configure.ac:14: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:57: error: possibly undefined macro: AC_DEFINE
configure.ac:64: error: possibly undefined macro: AC_SUBST
configure.ac:83: error: possibly undefined macro: AM_CONFIG_HEADER
configure.ac:84: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:144: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:235: error: possibly undefined macro: AM_PO_SUBDIRS
configure.ac:236: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:246: error: possibly undefined macro: AC_MSG_WARN
configure.ac:768: error: possibly undefined macro: AM_PATH_SDL
$ ./configure 
./configure: line 2228: KCEMU_SET_VERSION: command not found
configure: error: cannot find install-sh, install.sh, or shtool in config "."/config
$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
--------------------------------------------------------------------------

How can I build your software?

**Comment by glaubitz** [comment]
Try running `autoreconf` instead of `autoconf`. Don't forget to install the necessary build dependencies first.

**Comment by w8970** [comment]
Thank you for the quick answer.

I installed all the build dependencies from Debian: https://packages.debian.org/de/source/sid/kcemu, because on your site I found no list.

Unfortunately it did not work with autoreconf:
--------8<-----------------------------------------------8<----------------------------
$ git clean -xdf
$ autoreconf 
autoreconf: configure.ac: AM_GNU_GETTEXT is used, but not AM_GNU_GETTEXT_VERSION
configure.ac:235: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:235: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:235: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
configure.ac:17: error: required file 'config/compile' not found
configure.ac:17:   'automake --add-missing' can install 'compile'
configure.ac:15: error: required file 'config/config.guess' not found
configure.ac:15:   'automake --add-missing' can install 'config.guess'
configure.ac:15: error: required file 'config/config.sub' not found
configure.ac:15:   'automake --add-missing' can install 'config.sub'
configure.ac:84: error: required file 'config/install-sh' not found
configure.ac:84:   'automake --add-missing' can install 'install-sh'
configure.ac:84: error: required file 'config/missing' not found
configure.ac:84:   'automake --add-missing' can install 'missing'
src/cmd/Makefile.am: error: required file 'config/depcomp' not found
src/cmd/Makefile.am:   'automake --add-missing' can install 'depcomp'
parallel-tests: error: required file 'config/test-driver' not found
parallel-tests:   'automake --add-missing' can install 'test-driver'
autoreconf: automake failed with exit status: 1
$ ./configure
configure: error: cannot find install-sh, install.sh, or shtool in config "."/config
------8<------------------------------------------8<--------------------------------------

What can I do to build your SW?

**Comment by glaubitz** [comment]
Try passing `-i` to `autoreconf`, i.e. `autoreconf -i`.

From the manpage of `autoreconf`:

```
       -i, --install
              copy missing auxiliary files
```

**Comment by w8970** [comment]
Thank you, it worked and built after ./configure --prefix=$HOME && make.

Would it be a good idea to adapt the README[.de] to reflect this?
